name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository in the default path
      - name: Checkout repository
        uses: actions/checkout@main

      # Clean old builds
      - name: Clean old builds
        run: rm -rf $GITHUB_WORKSPACE/builds/*.cs3 || true

      # Setup JDK 11
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Build Plugins
      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      # Configure Git and push changes
      - name: Configure Git and push
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || echo "No changes to commit"
          git push
